version: '3.8'

services:
  thefoolcard_server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "61018:61018"
